# Generated by Django 4.2 on 2023-04-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like_to_post',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_like_to_comment',
        ),
    ]
